image: kitproject/gitpod-flutter-android:lastest
tasks:
  - init: >
    command: >
      flutter pub get
ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
