image: kitproject/gitpod-flutter:v1-13-6
tasks:
  - init: >
      flutter pub get
ports:
  - port: 8080
    onOpen: open-preview
vscode:
  extensions:
    - Dart-Code.dart-code@3.7.1:3XT4xvtPoRdNasA5smNMiA==
    - Dart-Code.flutter@3.7.1:gujVOCgsbgoN2/po8X1tfA==
    - alphabotsec.vscode-eclipse-keybindings@0.10.0:sHFK2cBlpLZsoaR/+m8Nig==
